### ISSUE TITLE
Reproduction score

### ISSUE THREAD

**Issue by jisoo0-0** [YufeiWang777/LRRU#15]
Hi, thank you for your wonderful work. 

I have tried copying the code from the LRRU Git Hub and getting your official score from scratch.
The score below is the best score I have got, but I have no idea how to get your official score. 

 test_Metric|  RMSE: 0.8624  MAE: 0.2202  iRMSE: 0.0026  iMAE: 0.0009  REL: 0.0119  D^1: 0.9970  D^2: 0.9990  D^3: 0.9996  

Thanks.

**Comment by sow1nk** [comment]
> Hi, thank you for your wonderful work.
> 
> I have tried copying the code from the LRRU Git Hub and getting your official score from scratch. The score below is the best score I have got, but I have no idea how to get your official score.
> 
> test_Metric| RMSE: 0.8624 MAE: 0.2202 iRMSE: 0.0026 iMAE: 0.0009 REL: 0.0119 D^1: 0.9970 D^2: 0.9990 D^3: 0.9996
> 
> Thanks.

Did you reproduce the test set results in the paper?
