### ISSUE TITLE
dataloaders utils.py -> read_depth

### ISSUE THREAD

**Issue by akaibai320** [YufeiWang777/LRRU#16]
Thank you for your nice work!
About the utils.py of dataloaders, the read_depth function has an assert:
assert (np.max(image_depth) == 0) or (np.max(image_depth) > 255), \
        "np.max(depth_png)={}, path={}".format(np.max(image_depth), file_name)
is this wrong? I think the max should be in 0 to 255.

**Comment by YufeiWang777** [comment]
Hi, the assert aims to make sure that the max is in 0 to 255.
