### ISSUE TITLE
Missing some code

### ISSUE THREAD

**Issue by chenlongwhu** [YufeiWang777/LRRU#4]
Hi, Thank you for your excellent work. 

But this repo seems incomplete. I can not find the "train_apex.py."

And "trian.sh" may be a typo mistake.

**Comment by YufeiWang777** [comment]
Thanks for your attention! I'm working on completing this github repository. It will take about a week.

**Comment by chenlongwhu** [comment]
> Thanks for your attention! I'm working on completing this github repository. It will take about a week.

Thank you for your reply, I can not wait to see the completed repo.
